### ISSUE TITLE
reconnect is using eth0 instead of specified interface

### ISSUE THREAD

**Issue by zivillian** [schwinn/khtool#2]
`send_command` calls `device.send_ssc` which automatically tries to reconnect to the speaker. Since there is no interface parameter specified it defaults to `%eth0` which is not available on my systems (windows/ubuntu)

I'm not sure if this should belong to [jj-wohlgemuth/pyssc](https://github.com/jj-wohlgemuth/pyssc), so feel free to close.

**Comment by schwinn** [comment]
I will upload a fixed version tomorrow.

**Comment by schwinn** [comment]
The fixed version is now online.

**Comment by zivillian** [comment]
It's working, thank you very much!
